name: Update News from n8n

on:
  repository_dispatch:
    types: [n8n-update]

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Update HTML file
        run: |
          echo '${{ github.event.client_payload.html_content }}' > index.html
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Auto-update: Latest news articles" || exit 0
          git push
